---

sa_cluster_operator: strimzi-cluster-operator
sa_cluster_operator_template: 010-ServiceAccount-strimzi-cluster-operator.yaml

clusterrole_cluster_operator_role: strimzi-cluster-operator-namespaced
clusterrole_cluster_operator_role_template: 020-ClusterRole-strimzi-cluster-operator-role.yaml

rolebinding_cluster_operator: strimzi-cluster-operator
rolebinding_cluster_operator_template: 020-RoleBinding-strimzi-cluster-operator.yaml

clusterrole_cluster_operator_role_global: strimzi-cluster-operator-global
clusterrole_cluster_operator_role_global_template: 021-ClusterRole-strimzi-cluster-operator-role.yaml

clusterrolebinding_cluster_operator: "strimzi-cluster-operator-{{ namespace_strimzi_operator }}"
clusterrolebinding_cluster_operator_template: 021-ClusterRoleBinding-strimzi-cluster-operator.yaml

clusterrole_kafka_broker: strimzi-kafka-broker
clusterrole_kafka_broker_template: 030-ClusterRole-strimzi-kafka-broker.yaml

clusterrolebinding_cluster_operator_kafka: "strimzi-cluster-operator-kafka-broker-delegation-{{ namespace_strimzi_operator }}"
clusterrolebinding_cluster_operator_kafka_template: 030-ClusterRoleBinding-strimzi-cluster-operator-kafka-broker-delegation.yaml

clusterrole_entity_operator: strimzi-entity-operator
clusterrole_entity_operator_template: 031-ClusterRole-strimzi-entity-operator.yaml

rolebinding_entity_operator: strimzi-cluster-operator-entity-operator-delegation
rolebinding_entity_operator_template: 031-RoleBinding-strimzi-cluster-operator-entity-operator-delegation.yaml

clusterrole_topic_operator: strimzi-topic-operator
clusterrole_topic_operator_template: 032-ClusterRole-strimzi-topic-operator.yaml

rolebinding_topic_operator: strimzi-cluster-operator-topic-operator-delegation
rolebinding_topic_operator_template: 032-RoleBinding-strimzi-cluster-operator-topic-operator-delegation.yaml

crd_kafka: kafkas.kafka.strimzi.io
crd_kafka_template: 040-Crd-kafka.yaml

crd_kafka_connect: kafkaconnects.kafka.strimzi.io
crd_kafka_connect_template: 041-Crd-kafkaconnect.yaml

crd_kafka_connect_s2i: kafkaconnects2is.kafka.strimzi.io
crd_kafka_connect_s2i_template: 042-Crd-kafkaconnects2i.yaml

crd_kafka_topic: kafkatopics.kafka.strimzi.io
crd_kafka_topic_template: 043-Crd-kafkatopic.yaml

crd_kafka_user: kafkausers.kafka.strimzi.io
crd_kafka_user_template: 044-Crd-kafkauser.yaml

crd_kafka_mirror_maker: kafkamirrormakers.kafka.strimzi.io
crd_kafka_mirror_maker_template: 045-Crd-kafkamirrormaker.yaml

crd_kafka_bridge: kafkabridges.kafka.strimzi.io
crd_kafka_bridge_template: 046-Crd-kafkabridge.yaml

crd_kafka_connector_name: kafkaconnectors.kafka.strimzi.io
crd_kafka_connector_template: 047-Crd-kafkaconnector.yaml

crd_kafka_mirrormaker2_name: kafkamirrormaker2s.kafka.strimzi.io
crd_kafka_mirrormaker2_template: 048-Crd-kafkamirrormaker2.yaml

deployment_cluster_operator: "{{ strimzi_cluster_operator }}"
deployment_cluster_operator_template: 050-Deployment-strimzi-cluster-operator.yaml

cluster_operator_resources_memory_limit: 256Mi
cluster_operator_resources_cpu_limit: 1000m
cluster_operator_resources_memory_request: 256Mi
cluster_operator_resources_cpu_request: 200m
