---

# cluster operator

- import_role:
    name: strimzi_cluster_operator

- import_role:
    name: strimzi_cluster_provisioner

- name: wait until cluster-operator is active
  shell: "{{ openshift_cli }} get deployment {{ strimzi_cluster_operator }} -o template --template={{ json_template }} -n {{ namespace }}"
  vars:
    json_template: '\{\{.status.readyReplicas\}\}'
  register: result
  until: result.stdout == "1"
  retries: 30
  delay: 10
  changed_when: false