---

- name: delete postgresql dc
  oc_obj:
    oc_binary: "{{ openshift_cli }}"
    state: absent
    name: "{{ postgresql_application_name }}"
    namespace: "{{ namespace }}"
    kind: dc

- name: delete postgresql service
  oc_obj:
    oc_binary: "{{ openshift_cli }}"
    state: absent
    name: "{{ postgresql_application_name }}"
    namespace: "{{ namespace }}"
    kind: service

- name: delete postgresql pvc
  oc_obj:
    oc_binary: "{{ openshift_cli }}"
    state: absent
    name: "{{ postgresql_application_name}}"
    namespace: "{{ namespace }}"
    kind: pvc

- name: delete postgresql secret
  oc_secret:
    oc_binary: "{{ openshift_cli }}"
    namespace: "{{ namespace }}"
    name: "{{ postgresql_application_name }}"
    state: absent

- name: delete postgresql init configmap
  oc_configmap:
    oc_binary: "{{ openshift_cli }}"
    state: absent
    name: "{{ postgresql_init_configmap }}"
    namespace: "{{ namespace }}"

- name: delete {{ postgresql_service_account }} service account
  oc_serviceaccount:
    oc_binary: "{{ openshift_cli }}"
    state: absent
    name: "{{ postgresql_service_account }}"
    namespace: "{{ namespace }}"