---

- name: Deploy Pipeline for Assignment Rules Kjar
  hosts: localhost
  connection: local
  gather_facts: false
  run_once: true
  vars_files:
    - group_vars/services.yml
    - group_vars/tools.yml

  tasks:
    - set_fact:
        resources_dir: "{{ resources_base_dir }}/assignment-rules"
        work_dir_name: assignment-rules
    - include_role:
        name: ../roles/openshift_assignment_rules
      when: >
        ACTION is not defined or
        ACTION is none or
        ACTION|trim() == "" or
        ACTION|trim() == "install"
    - include_role:
        name: ../roles/openshift_assignment_rules
        tasks_from: uninstall
      when: >
        ACTION is defined and
        ACTION|trim() == "uninstall"