---

- name: Deploy Pipeline for Incident Process Kjar
  hosts: localhost
  connection: local
  gather_facts: false
  run_once: true
  vars_files:
    - group_vars/services.yml
    - group_vars/tools.yml

  tasks:
    - set_fact:
       resources_dir: "{{ resources_base_dir }}/incident-process"
       work_dir_name: incident-service
    - include_role:
        name: ../roles/openshift_incident_process
      when: >
        ACTION is not defined or
        ACTION is none or
        ACTION|trim() == "" or
        ACTION|trim() == "install"
    - include_role:
        name: ../roles/openshift_incident_process
        tasks_from: uninstall
      when: >
        ACTION is defined and
        ACTION|trim() == "uninstall"