---

- name: Deploy Kafka Cluster
  hosts: localhost
  connection: local
  gather_facts: false
  run_once: true
  vars_files:
    - group_vars/kafka_cluster.yml

  tasks:
    - set_fact:
        work_dir_name: kafka-cluster
    - include_role:
        name: ../roles/openshift_kafka_cluster
      when: >
        ACTION is not defined or
        ACTION is none or
        ACTION|trim() == "" or
        ACTION|trim() == "create"
    - include_role:
        name: ../roles/openshift_kafka_cluster
        tasks_from: uninstall
      when: >
        ACTION is defined and
        ACTION|trim() == "uninstall"