---

- name: Deploy Postgresql
  hosts: localhost
  connection: local
  gather_facts: false
  run_once: true
  vars_files:
    - group_vars/postgresql.yml

  tasks:
    - set_fact:
        namespace: "{{ namespace_postgresql }}"
        resources_dir: "{{ resources_base_dir }}/postgresql"
        work_dir_name: postgresql
    - include_role:
        name: ../roles/openshift_postgresql
      when: >
        ACTION is not defined or
        ACTION is none or
        ACTION|trim() == "" or
        ACTION|trim() == "install"
    - include_role:
        name: ../roles/openshift_postgresql
        tasks_from: uninstall
      when: >
        ACTION is defined and
        ACTION|trim() == "uninstall"