---

- name: Deploy Process Service
  hosts: localhost
  connection: local
  gather_facts: false
  run_once: true
  vars_files:
    - group_vars/services.yml
    - group_vars/kafka_cluster.yml
    - group_vars/tools.yml

  tasks:
    - set_fact:
        namespace: "{{ namespace_services }}"
        resources_dir: "{{ resources_base_dir }}/process-service"
        work_dir_name: process-service
    - include_role:
        name: ../roles/openshift_process_service
      when: >
        ACTION is not defined or
        ACTION is none or
        ACTION|trim() == "" or
        ACTION|trim() == "install"
    - include_role:
        name: ../roles/openshift_process_service
        tasks_from: uninstall
      when: >
        ACTION is defined and
        ACTION|trim() == "uninstall"