---

project_admin: user1

home_dir: "{{ playbook_dir }}/.."

# resources dir
resources_base_dir: "{{ home_dir }}/resources"

# oc executable
openshift_cli: oc

project_name: "{{ project_admin }}-er-demo"

monitoring_label: prometheus

# If set to True, then every user that creates an account in Emergency Response demo will automatically be a "realm-admin"
set_realm_admin_as_default: False
