---

namespace_strimzi_operator: kafka-operator-erd
namespace_kafka_cluster: "{{ project_name }}"

strimzi_cluster_operator: strimzi-cluster-operator

kafka_cluster: kafka-cluster

kafka_topics: >
  [{"name": "topic-incident-event", "partitions": "15", "replicas": "2", "config": "{}"},
   {"name": "topic-priority-zone-event", "partitions": "15", "replicas": "2", "config": "{}"}
   {"name": "topic-incident-command", "partitions": "15", "replicas": "2", "config": "{}"},
   {"name": "topic-mission-command", "partitions": "15", "replicas": "2", "config": "{}"},
   {"name": "topic-mission-event", "partitions": "15", "replicas": "2", "config": "{}"},
   {"name": "topic-responder-command", "partitions": "15", "replicas": "2", "config": "{}"},
   {"name": "topic-responder-event", "partitions": "15", "replicas": "2", "config": "{}"},
   {"name": "topic-responder-location-update", "partitions": "15", "replicas": "2", "config": "{}"}]