---

namespace_postgresql: "{{ project_name }}"

postgresql_init_scripts:
  - https://raw.githubusercontent.com/NAPS-emergency-response-project/sql-scripts/master/naps_emergency_response_with_data.sql

postgresql_username: naps
postgresql_password: naps
postgresql_database: naps_emergency_response

postgresql_application_name: postgresql
postgresql_credentials_secret: "{{ postgresql_application_name }}-credentials"