---

namespace_services: "{{ project_name }}"

assignment_rules_application_name: "{{ project_admin }}-assignment-rules"
assignment_rules_model_application_name: "{{ project_admin }}-assignment-rules-model"
incident_process_application_name: "{{ project_admin }}-incident-process"
incident_service_application_name: "{{ project_admin }}-incident-service"
mission_service_application_name: "{{ project_admin }}-mission-service"
process_service_application_name: "{{ project_admin }}-process-service"
responder_service_application_name: "{{ project_admin }}-responder-service"
responder_simulator_service_application_name: "{{ project_admin }}-responder-simulator"
emergency_console_application_name: "{{ project_admin }}-emergency-console"
process_viewer_application_name: "{{ project_admin }}-process-viewer"
incident_priority_service_application_name: "{{ project_admin }}-incident-priority-service"
disaster_simulator_service_application_name: "{{ project_admin }}-disaster-simulator"
process_service_postgresql_username: "{{ project_admin }}-rhpam"
process_service_postgresql_password: "{{ project_admin }}-rhpam"
process_service_postgresql_database: "{{ project_admin }}-rhpam"
process_service_postgresql_service_name: "{{ project_admin }}-process-service-postgresql"
