---

# datagrid operator
datagrid_operator_name: infinispan-operator
datagrid_operatorgroup_name: datagrid-operator
datagrid_subscription_name: datagrid
datagrid_operator_package_name: datagrid
datagrid_catalog_source: redhat-operators
datagrid_catalog_source_namespace: openshift-marketplace
replica_status: '\{\{.status.readyReplicas\}\}'

datagrid_connect_secret: dg-connect-secret

number_of_replicas: 3
total_container_memory: 512Mi
total_container_cpu: 1000m

container_memory_request: 512
container_cpu_request: 500
total_container_storage: 1

datagrid_defaultchannel: 8.1.x

datagrid_route_name: datagrid-service-external
