---

monitoring_kafka_servicemonitor_template: emergency-response-kafka-servicemonitor.yml
monitoring_application_servicemonitor_template: emergency-response-application-servicemonitor.yml 
monitoring_actuator_servicemonitor_template: emergency-response-actuator-servicemonitor.yml 
monitoring_grafana_dashboard_template: emergency-response-grafanadashboard.yml
