---

apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: {{ imagestream_name }}
  labels:
    app: {{ application_name }}
spec:
  dockerImageRepository: {{ incident_priority_service_image }}