---

- import_role:
    name: openshift_apply_resource
  vars:
    resource_type: serviceaccount
    resource: "{{sa_cluster_operator }}"
    resource_template: "{{ resources_dir }}/cluster-operator/{{ sa_cluster_operator_template }}"
    resource_namespace: "{{ namespace_strimzi_operator }}"

- import_role:
    name: openshift_apply_cluster_resource
  vars:
    resource_type: clusterrole
    resource: "{{ clusterrole_cluster_operator_role }}"
    resource_template: "{{ resources_dir }}/cluster-operator/{{ clusterrole_cluster_operator_role_template }}"

- import_role:
    name: openshift_apply_cluster_resource
  vars:
    resource_type: clusterrole
    resource: "{{ clusterrole_cluster_operator_role_global }}"
    resource_template: "{{ resources_dir }}/cluster-operator/{{ clusterrole_cluster_operator_role_global_template }}"

- name: copy clusterrolebinding template to work directory
  template:
    src: "{{ resources_dir }}/cluster-operator/{{ clusterrolebinding_cluster_operator_template }}"
    dest: "{{ work_dir }}/{{ clusterrolebinding_cluster_operator_template }}"

- import_role:
    name: openshift_apply_cluster_resource
  vars:
    resource_type: clusterrolebinding
    resource: "{{ clusterrolebinding_cluster_operator }}"
    resource_template: "{{ work_dir }}/{{ clusterrolebinding_cluster_operator_template }}"

- import_role:
    name: openshift_apply_cluster_resource
  vars:
    resource_type: clusterrole
    resource: "{{ clusterrole_kafka_broker }}"
    resource_template: "{{ resources_dir }}/cluster-operator/{{ clusterrole_kafka_broker_template }}"

- name: copy clusterrolebinding template to work directory
  template:
    src: "{{ resources_dir }}/cluster-operator/{{ clusterrolebinding_cluster_operator_kafka_template }}"
    dest: "{{ work_dir }}/{{ clusterrolebinding_cluster_operator_kafka_template }}"

- import_role:
    name: openshift_apply_cluster_resource
  vars:
    resource_type: clusterrolebinding
    resource: "{{ clusterrolebinding_cluster_operator_kafka }}"
    resource_template: "{{ work_dir }}/{{ clusterrolebinding_cluster_operator_kafka_template }}"

- import_role:
    name: openshift_apply_cluster_resource
  vars:
    resource_type: clusterrole
    resource: "{{ clusterrole_entity_operator }}"
    resource_template: "{{ resources_dir }}/cluster-operator/{{ clusterrole_entity_operator_template }}"

- import_role:
    name: openshift_apply_cluster_resource
  vars:
    resource_type: clusterrole
    resource: "{{ clusterrole_topic_operator }}"
    resource_template: "{{ resources_dir }}/cluster-operator/{{ clusterrole_topic_operator_template }}"

- import_role:
    name: openshift_apply_cluster_resource
  vars:
    resource_type: crd
    resource: "{{ crd_kafka }}"
    resource_template: "{{ resources_dir }}/cluster-operator/{{ crd_kafka_template }}"

- import_role:
    name: openshift_apply_cluster_resource
  vars:
    resource_type: crd
    resource: "{{ crd_kafka_connect }}"
    resource_template: "{{ resources_dir }}/cluster-operator/{{ crd_kafka_connect_template }}"

- import_role:
    name: openshift_apply_cluster_resource
  vars:
    resource_type: crd
    resource: "{{ crd_kafka_connect_s2i }}"
    resource_template: "{{ resources_dir }}/cluster-operator/{{ crd_kafka_connect_s2i_template }}"

- import_role:
    name: openshift_apply_cluster_resource
  vars:
    resource_type: crd
    resource: "{{ crd_kafka_topic }}"
    resource_template: "{{ resources_dir }}/cluster-operator/{{ crd_kafka_topic_template }}"

- import_role:
    name: openshift_apply_cluster_resource
  vars:
    resource_type: crd
    resource: "{{ crd_kafka_user }}"
    resource_template: "{{ resources_dir }}/cluster-operator/{{ crd_kafka_user_template }}"

- import_role:
    name: openshift_apply_cluster_resource
  vars:
    resource_type: crd
    resource: "{{ crd_kafka_mirror_maker }}"
    resource_template: "{{ resources_dir }}/cluster-operator/{{ crd_kafka_mirror_maker_template }}"

- import_role:
    name: openshift_apply_cluster_resource
  vars:
    resource_type: crd
    resource: "{{ crd_kafka_bridge }}"
    resource_template: "{{ resources_dir }}/cluster-operator/{{ crd_kafka_bridge_template }}"

# kafka cluster project
- name: create project {{ namespace_kafka_cluster }}
  oc_project:
    state: present
    oc_binary: "{{ openshift_cli }}"
    name: "{{ namespace_kafka_cluster }}"

- name: copy rolebinding template to work directory
  template:
    src: "{{ resources_dir }}/cluster-operator/{{ rolebinding_cluster_operator_template }}"
    dest: "{{ work_dir }}/{{ rolebinding_cluster_operator_template }}"

- import_role:
    name: openshift_apply_resource
  vars:
    resource_type: rolebinding
    resource: "{{ rolebinding_cluster_operator }}"
    resource_template: "{{ work_dir }}/{{ rolebinding_cluster_operator_template }}"
    resource_namespace: "{{ namespace_kafka_cluster }}"

- name: copy rolebinding template to work directory
  template:
    src: "{{ resources_dir }}/cluster-operator/{{ rolebinding_entity_operator_template }}"
    dest: "{{ work_dir }}/{{ rolebinding_entity_operator_template }}"

- import_role:
    name: openshift_apply_resource
  vars:
    resource_type: rolebinding
    resource: "{{ rolebinding_entity_operator }}"
    resource_template: "{{ work_dir }}/{{ rolebinding_entity_operator_template }}"
    resource_namespace: "{{ namespace_kafka_cluster }}"

- name: copy rolebinding template to work directory
  template:
    src: "{{ resources_dir }}/cluster-operator/{{ rolebinding_topic_operator_template }}"
    dest: "{{ work_dir }}/{{ rolebinding_topic_operator_template }}"

- import_role:
    name: openshift_apply_resource
  vars:
    resource_type: rolebinding
    resource: "{{ rolebinding_topic_operator }}"
    resource_template: "{{ work_dir }}/{{ rolebinding_topic_operator_template }}"
    resource_namespace: "{{ namespace_kafka_cluster }}"

- name: copy deployment template to work directory
  template:
    src: "{{ resources_dir }}/cluster-operator/{{ deployment_cluster_operator_template }}"
    dest: "{{ work_dir }}/{{ deployment_cluster_operator_template }}"

- import_role:
    name: openshift_apply_resource
  vars:
    resource_type: deployment
    resource: "{{ deployment_cluster_operator }}"
    resource_template: "{{ work_dir }}/{{ deployment_cluster_operator_template }}"
    resource_namespace: "{{ namespace_strimzi_operator }}"

- name: Provide ability to strimzi operator to view all namespaces
  shell: oc adm policy add-cluster-role-to-user strimzi-cluster-operator-namespaced -z strimzi-cluster-operator -n {{ namespace_strimzi_operator }}
- shell: oc adm policy add-cluster-role-to-user strimzi-entity-operator -z strimzi-cluster-operator -n {{ namespace_strimzi_operator }}
- shell: oc adm policy add-cluster-role-to-user strimzi-topic-operator -z strimzi-cluster-operator -n {{ namespace_strimzi_operator }}
