---

- name: "remove {{ deployment_cluster_operator }} deployment"
  oc_obj:
    state: absent
    oc_binary: "{{ openshift_cli }}"
    name: "{{ deployment_cluster_operator }}"
    kind: deployment
    namespace: "{{ namespace_strimzi_operator }}"
  when: uninstall_cluster_resources|bool == true

- name: "remove {{ crd_kafka }} crd"
  oc_obj:
    state: absent
    oc_binary: "{{ openshift_cli }}"
    name: "{{ crd_kafka }}"
    kind: crd
  when: uninstall_cluster_resources|bool == true

- name: "remove {{ crd_kafka_connect }} crd"
  oc_obj:
    state: absent
    oc_binary: "{{ openshift_cli }}"
    name: "{{ crd_kafka_connect }}"
    kind: crd
  when: uninstall_cluster_resources|bool == true

- name: "remove {{ crd_kafka_connect_s2i }} crd"
  oc_obj:
    state: absent
    oc_binary: "{{ openshift_cli }}"
    name: "{{ crd_kafka_connect_s2i }}"
    kind: crd
  when: uninstall_cluster_resources|bool == true

- name: "remove {{ crd_kafka_topic }} crd"
  oc_obj:
    state: absent
    oc_binary: "{{ openshift_cli }}"
    name: "{{ crd_kafka_topic }}"
    kind: crd
  when: uninstall_cluster_resources|bool == true

- name: "remove {{ crd_kafka_user }} crd"
  oc_obj:
    state: absent
    oc_binary: "{{ openshift_cli }}"
    name: "{{ crd_kafka_user }}"
    kind: crd
  when: uninstall_cluster_resources|bool == true

- name: "remove {{ crd_kafka_mirror_maker }} crd"
  oc_obj:
    state: absent
    oc_binary: "{{ openshift_cli }}"
    name: "{{ crd_kafka_mirror_maker }}"
    kind: crd
  when: uninstall_cluster_resources|bool == true

- name: "remove {{ crd_kafka_bridge }} crd"
  oc_obj:
    state: absent
    oc_binary: "{{ openshift_cli }}"
    name: "{{ crd_kafka_bridge }}"
    kind: crd
  when: uninstall_cluster_resources|bool == true

- name: "remove {{ crd_kafka_connector_name }} crd"
  oc_obj:
    state: absent
    oc_binary: "{{ openshift_cli }}"
    name: "{{ crd_kafka_connector_name }}"
    kind: crd
  when: uninstall_cluster_resources|bool == true

- name: "remove {{ crd_kafka_mirrormaker2_name }} crd"
  oc_obj:
    state: absent
    oc_binary: "{{ openshift_cli }}"
    name: "{{ crd_kafka_mirrormaker2_name }}"
    kind: crd
  when: uninstall_cluster_resources|bool == true

- name: "remove {{ clusterrole_topic_operator }} clusterrole"
  oc_obj:
    state: absent
    oc_binary: "{{ openshift_cli }}"
    name: "{{ clusterrole_topic_operator }}"
    kind: clusterrole
  when: uninstall_cluster_resources|bool == true

- name: "remove {{ clusterrole_entity_operator }} clusterrole"
  oc_obj:
    state: absent
    oc_binary: "{{ openshift_cli }}"
    name: "{{ clusterrole_entity_operator }}"
    kind: clusterrole
  when: uninstall_cluster_resources|bool == true

- name: "remove {{ clusterrolebinding_cluster_operator_kafka }} clusterrolebinding"
  oc_obj:
    state: absent
    oc_binary: "{{ openshift_cli }}"
    name: "{{ clusterrolebinding_cluster_operator_kafka }}"
    kind: clusterrolebinding

- name: "remove {{ clusterrole_kafka_broker }} clusterrole"
  oc_obj:
    state: absent
    oc_binary: "{{ openshift_cli }}"
    name: "{{ clusterrole_kafka_broker }}"
    kind: clusterrole
  when: uninstall_cluster_resources|bool == true

- name: "remove {{ clusterrolebinding_cluster_operator }} clusterrolebinding"
  oc_obj:
    state: absent
    oc_binary: "{{ openshift_cli }}"
    name: "{{ clusterrolebinding_cluster_operator }}"
    kind: clusterrolebinding

- name: "remove {{ clusterrole_cluster_operator_role }} clusterrole"
  oc_obj:
    state: absent
    oc_binary: "{{ openshift_cli }}"
    name: "{{ clusterrole_cluster_operator_role_global }}"
    kind: clusterrole
  when: uninstall_cluster_resources|bool == true

- name: "remove {{ clusterrole_cluster_operator_role }} clusterrole"
  oc_obj:
    state: absent
    oc_binary: "{{ openshift_cli }}"
    name: "{{ clusterrole_cluster_operator_role }}"
    kind: clusterrole
  when: uninstall_cluster_resources|bool == true

- name: "remove serviceaccount {{ sa_cluster_operator }}"
  oc_obj:
    state: absent
    oc_binary: "{{ openshift_cli }}"
    name: "{{ sa_cluster_operator }}"
    kind: serviceaccount
    namespace: "{{ namespace_strimzi_operator }}"

- name: remove cluster operator clusterrolebinding
  oc_obj:
    oc_binary: "{{ openshift_cli }}"
    state: absent
    name: strimzi-cluster-operator-namespaced
    kind: clusterrolebinding

- name: remove entity operator clusterrole binding
  oc_obj:
    oc_binary: "{{ openshift_cli }}"
    state: absent
    name: strimzi-cluster-operator-entity-operator-delegation
    kind: clusterrolebinding

- name: remove topic operator clusterrolebinding
  oc_obj:
    oc_binary: "{{ openshift_cli }}"
    state: absent
    name: strimzi-cluster-operator-topic-operator-delegation
    kind: clusterrolebinding