---

- name: create {{ service_account }} service account for {{ application_name }} application
  oc_serviceaccount:
    oc_binary: "{{ openshift_cli }}"
    state: present
    name: "{{ service_account }}"
    namespace: "{{ namespace }}"

- name: create {{ emergency_console_config_configmap }} configmap
  oc_configmap:
    oc_binary: "{{ openshift_cli }}"
    state: present
    namespace: "{{ namespace }}"
    name: "{{ emergency_console_config_configmap }}"
    from_literal:
      TOKEN: "{{ emergency_console_config_map_token }}"
      POLLING: "{{ emergency_console_config_polling }}"
      KAFKA_HOST: "{{ kafka_bootstrap_address }}"
      KAFKA_GROUP_ID: "{{ kafka_groupid }}"
      KAFKA_TOPIC: "{{ kafka_topic_mission_event }},{{ kafka_topic_responder_location_update }},{{ kafka_topic_incident_event }},{{ kafka_topic_incident_command }},{{ kafka_topic_responder_event }},{{ kafka_topic_responder_command }}"
      INCIDENT: "http://{{ incident_service_application_name }}.{{ namespace }}.svc:8080"
      RESPONDER: "http://{{ responder_service_application_name }}.{{ namespace }}.svc:8080"
      MISSION: "http://{{ mission_service_application_name }}.{{ namespace }}.svc:8080"
      PROCESS_VIEWER: "http://{{ process_viewer_application_name }}.{{ namespace }}.svc:8080"
      RESPONDER_SIMULATOR: "http://{{ responder_simulator_service_application_name }}.{{ namespace }}.svc:8080"
      DISASTER_SIMULATOR: "http://{{ disaster_simulator_service_application_name }}.{{ namespace }}.svc:8080"
      PRIORITY: "http://{{ incident_priority_service_application_name }}.{{ namespace }}.svc:8080"
      DISASTER: "http://{{ disaster_service_application_name }}.{{ namespace }}.svc:8080"

- import_tasks: deploy_from_source.yml
  when: deploy_from is defined and deploy_from == "source"

- import_tasks: deploy_from_image.yml
  when: deploy_from is defined and deploy_from == "image"
