---

- set_fact:
    github_secret: "{{ lookup('password', work_dir + '/github chars=ascii_letters,digits length=8') }}"

- set_fact:
    generic_secret: "{{ lookup('password', work_dir + '/generic chars=ascii_letters,digits length=8') }}"

- name: create {{ service_account }} service account for {{ application_name }} application
  oc_serviceaccount:
    oc_binary: "{{ openshift_cli }}"
    state: present
    name: "{{ service_account }}"
    namespace: "{{ namespace }}"

- name: copy build config template
  template:
    src: "{{ resources_dir }}/{{ buildconfig_template }}"
    dest: "{{ work_dir }}/{{ buildconfig_template }}"

- name: create build config in the {{ namespace }} namespace
  oc_obj:
    oc_binary: "{{ openshift_cli }}"
    state: present
    namespace: "{{ namespace }}"
    kind: buildconfig
    name: "{{ buildconfig_name }}"
    files:
      - "{{ work_dir }}/{{ buildconfig_template }}"

- name: copy imagestream template
  template:
    src: "{{ resources_dir }}/{{ imagestream_template }}"
    dest: "{{ work_dir }}/{{ imagestream_template }}"

- name: create output imagestream in the {{ namespace_tools }} project
  oc_obj:
    oc_binary: "{{ openshift_cli }}"
    state: present
    namespace: "{{ namespace_tools }}"
    kind: imagestream
    name: "{{ imagestream_name }}"
    files:
      - "{{ work_dir }}/{{ imagestream_template }}"

- name: create output imagestream in the {{ namespace }} project
  oc_obj:
    oc_binary: "{{ openshift_cli }}"
    state: present
    namespace: "{{ namespace }}"
    kind: imagestream
    name: "{{ imagestream_name }}"
    files:
      - "{{ work_dir }}/{{ imagestream_template }}"

- name: give edit permissions to system:serviceaccount:{{ namespace_tools }}:jenkins in project {{ namespace }}
  oc_adm_policy_user:
    state: present
    oc_binary: "{{ openshift_cli }}"
    rolebinding_name: jenkins-edit
    namespace: "{{ namespace }}"
    resource_kind: role
    user: "system:serviceaccount:{{ namespace_tools }}:jenkins"
    resource_name: edit

- name: copy pipeline template
  template:
    src: "{{ resources_dir }}/{{ pipeline_buildconfig_template }}"
    dest: "{{ work_dir }}/{{ pipeline_buildconfig_template }}"

- name: create the {{ pipeline_buildconfig_name }} pipeline in the {{ namespace }} project
  oc_obj:
    state: present
    oc_binary: "{{ openshift_cli }}"
    name: "{{ pipeline_buildconfig_name }}"
    namespace: "{{ namespace_tools }}"
    kind: bc
    files:
      - "{{ work_dir }}/{{ pipeline_buildconfig_template }}"

- name: create {{ emergency_console_config_configmap }} configmap
  oc_configmap:
    oc_binary: "{{ openshift_cli }}"
    state: present
    namespace: "{{ namespace }}"
    name: "{{ emergency_console_config_configmap }}"
    from_literal:
      TOKEN: "{{ emergency_console_config_map_token }}"
      POLLING: "{{ emergency_console_config_polling }}"
      KAFKA_HOST: "{{ kafka_bootstrap_address }}"
      KAFKA_GROUP_ID: "{{ kafka_groupid }}"
      KAFKA_TOPIC: "{{ kafka_topic_mission_event }},{{ kafka_topic_responder_location_update }},{{ kafka_topic_incident_event }},{{ kafka_topic_incident_command }},{{ kafka_topic_responder_event }},{{ kafka_topic_responder_command }}"
      INCIDENT: "http://{{ incident_service_application_name }}.{{ namespace }}.svc:8080"
      RESPONDER: "http://{{ responder_service_application_name }}.{{ namespace }}.svc:8080"
      MISSION: "http://{{ mission_service_application_name }}.{{ namespace }}.svc:8080"
      PROCESS_VIEWER: "http://{{ process_viewer_application_name }}.{{ namespace }}.svc:8080"
      RESPONDER_SIMULATOR: "http://{{ responder_simulator_service_application_name }}.{{ namespace }}.svc:8080"

- name: copy application template
  template:
    src: "{{ resources_dir }}/{{ application_template }}"
    dest: "{{ work_dir }}/{{ application_template }}"

- name: check if {{ application_name }} application is deployed
  oc_obj:
    oc_binary: "{{ openshift_cli }}"
    state: list
    namespace: "{{ namespace }}"
    name: "{{ application_name }}"
    kind: dc
  register: result

- name: deploy {{ application_name }} application
  oc_list:
    oc_binary: "{{ openshift_cli }}"
    state: present
    namespace: "{{ namespace }}"
    files:
      - "{{ work_dir }}/{{ application_template }}"
  when: result.ansible_module_results.stderr is defined and result.ansible_module_results.stderr != ""
